export { KiriteClient } from "./client";

export type {
  EncryptedAmount,
  DecryptedTransfer,
  CurvePoint,
  Scalar,
  ElGamalKeypair,
  ElGamalCiphertext,
  RangeProof,
  EqualityProof,
  TransferProof,
  DepositProof,
  WithdrawProof,
  ShieldPoolConfig,
  ShieldPoolState,
  DepositNote,
  MerklePath,
  MerkleNode,
  StealthMetaAddress,
  StealthAddress,
  StealthPayment,
  StealthRegistryEntry,
  KiriteClientConfig,
  TransactionOptions,
  RetryConfig,
  ConfidentialTransferParams,
  ConfidentialTransferResult,
  DepositParams,
  DepositResult,
  WithdrawParams,
  WithdrawResult,
  GenerateStealthParams,
  ScanStealthParams,
  ConfidentialTransferEvent,
  ShieldDepositEvent,
  ShieldWithdrawEvent,
  StealthAnnouncementEvent,
} from "./types";

export {
  KIRITE_PROGRAM_ID,
  KIRITE_DEVNET_PROGRAM_ID,
  SEEDS,
  DEFAULT_TREE_DEPTH,
  DEFAULT_DENOMINATIONS,
  ELGAMAL,
  PROOF_SIZES,
  STEALTH,
  RPC_ENDPOINTS,
  DEFAULT_RETRY_CONFIG,
  DEFAULT_CONFIRM_TIMEOUT,
  COMPUTE_BUDGET,
  ZERO_VALUE,
  GENERATOR_POINT,
  MAX_MEMO_LENGTH,
} from "./constants";

export {
  KiriteError,
  WalletNotConnectedError,
  ConnectionError,
  TransactionError,
  ConfirmationTimeoutError,
  SimulationError,
  EncryptionError,
  ProofError,
  ProofVerificationError,
  InvalidAmountError,
  PoolNotFoundError,
  PoolPausedError,
  InvalidDenominationError,
  NullifierSpentError,
  TreeFullError,
  StealthAddressError,
  RegistryNotFoundError,
  AccountNotFoundError,
  InsufficientBalanceError,
  parseTransactionError,
  isKiriteError,
} from "./errors";

export {
  encryptAmount,
  decryptAmount,
  createCiphertext,
  pedersenCommit,
  verifyPedersenCommitment,
  encryptBalance,
  addEncryptedAmounts,
  constantTimeEquals,
  deriveElGamalPublicKey,
  serializeEncryptedAmount,
  deserializeEncryptedAmount,
  generateRangeProof,
  verifyRangeProof,
  generateEqualityProof,
  verifyEqualityProof,
  generateBalanceProof,
  generateTransferProof,
  verifyTransferProof,
  serializeTransferProof,
  deserializeTransferProof,
  deriveConfidentialAccountAddress,
  deriveEncryptedBalanceAddress,
  buildInitConfidentialAccountInstruction,
  buildConfidentialTransferInstruction,
  executeConfidentialTransfer,
  decryptIncomingTransfers,
  getConfidentialBalance,
} from "./confidential";

export {
  derivePoolAddress,
  derivePoolTokenAddress,
  derivePoolAuthorityAddress,
  deriveNullifierAddress,
  parsePoolState,
  fetchPoolState,
  fetchPoolsByMint,
  fetchAllPools,
  isNullifierSpent,
  computeMerkleRoot,
  computeMerklePath,
  verifyMerklePath,
  hashPair,
  computeLeafHash,
  getZeroHashes,
  generateDepositSecrets,
  computeFinalNullifier,
  generateDepositProof,
  buildDepositInstruction,
  executeDeposit,
  serializeDepositNote,
  deserializeDepositNote,
  generateWithdrawProof,
  buildWithdrawInstruction,
  executeWithdraw,
  verifyWithdrawProof,
  estimateRelayerFee,
} from "./shield-pool";

export {
  generateStealthMetaAddress,
  generateStealthAddress,
  checkViewTag,
  deriveStealthSpendingKey,
  recoverStealthAddress,
  serializeStealthMetaAddress,
  deserializeStealthMetaAddress,
  validateStealthMetaAddress,
  scanStealthPayments,
  scanStealthPaymentsFromLogs,
  calculateStealthBalances,
  deriveRegistryAddress,
  deriveAnnouncementAddress,
  parseRegistryEntry,
  fetchRegistryEntry,
  fetchAllRegistryEntries,
  lookupStealthMetaAddress,
  buildRegisterInstruction,
  buildUpdateRegistryInstruction,
  buildAnnouncementInstruction,
  registerStealthMetaAddress,
  publishStealthAnnouncement,
} from "./stealth";

export {
  createConnection,
  validateConnection,
  fetchAccountOrThrow,
  fetchMultipleAccounts,
  fetchProgramAccounts,
  getTokenBalance,
  getSolBalance,
  confirmTransaction,
  getCurrentSlot,
  getBlockTime,
  resolveEndpoint,
  getRecentSignatures,
  buildTransaction,
  buildVersionedTransaction,
  signAndSendTransaction,
  sendAndConfirmTransaction,
  simulateTransaction,
  getTransactionLogs,
  createMemoInstruction,
  estimateTransactionFee,
  deriveKeypair,
  deriveElGamalKeypair,
  deriveViewingKeypair,
  deriveSpendingKeypair,
  generateKeypair,
  loadKeypairFromJson,
  keypairToJson,
  computeSharedSecret,
  randomBytes,
  hash256,
} from "./utils";
