/**
 * @kirite/sdk
 *
 * TypeScript surface for the KIRITE privacy protocol on Solana.
 *
 * v3 deposit / proof / withdraw is implemented in `kirite-zk.mjs`
 * (Node) and `staking.mjs` (staking program). Import those files
 * directly for the actual ZK helpers; this index exports the typed
 * primitives, errors, constants, and stealth-address utilities.
 */

export type {
  ShieldPoolState,
  DepositNote,
  MerklePath,
  MerkleNode,
  Groth16Proof,
  WithdrawPublicInputs,
  StealthMetaAddress,
  StealthAddress,
  StealthPayment,
  StealthRegistryEntry,
  KiriteClientConfig,
  TransactionOptions,
  RetryConfig,
  DepositParams,
  DepositResult,
  WithdrawParams,
  WithdrawResult,
  ScanStealthParams,
  DepositCommittedEvent,
  WithdrawEvent,
  StealthAnnouncementEvent,
} from "./types";

export {
  KIRITE_PROGRAM_ID,
  KIRITE_DEVNET_PROGRAM_ID,
  KIRITE_STAKING_PROGRAM_ID,
  KIRITE_TOKEN_MINT,
  SEEDS,
  DEFAULT_TREE_DEPTH,
  MAX_TREE_DEPTH,
  DEFAULT_TREE_CAPACITY,
  DEFAULT_DENOMINATIONS,
  STEALTH,
  RPC_ENDPOINTS,
  DEFAULT_RETRY_CONFIG,
  DEFAULT_CONFIRM_TIMEOUT,
  COMPUTE_BUDGET,
  BN254_FIELD_MODULUS,
  ZERO_VALUE,
  DISCRIMINATOR_SIZE,
  MAX_MEMO_LENGTH,
} from "./constants";

export {
  KiriteError,
  WalletNotConnectedError,
  ConnectionError,
  TransactionError,
  ConfirmationTimeoutError,
  SimulationError,
  ProofError,
  InvalidAmountError,
  PoolNotFoundError,
  PoolFrozenError,
  InvalidDenominationError,
  NullifierSpentError,
  TreeFullError,
  StealthAddressError,
  RegistryNotFoundError,
  AccountNotFoundError,
  InsufficientBalanceError,
  RelayerError,
  isKiriteError,
  parseTransactionError,
} from "./errors";

export {
  generateStealthMetaAddress,
  generateStealthAddress,
  checkViewTag,
  deriveStealthSpendingKey,
  recoverStealthAddress,
  serializeStealthMetaAddress,
  deserializeStealthMetaAddress,
  validateStealthMetaAddress,
  scanStealthPayments,
  scanStealthPaymentsFromLogs,
  calculateStealthBalances,
  deriveRegistryAddress,
  deriveAnnouncementAddress,
  parseRegistryEntry,
  fetchRegistryEntry,
  fetchAllRegistryEntries,
  lookupStealthMetaAddress,
  buildRegisterInstruction,
  buildUpdateRegistryInstruction,
  buildAnnouncementInstruction,
  registerStealthMetaAddress,
  publishStealthAnnouncement,
} from "./stealth";

export {
  createConnection,
  validateConnection,
  fetchAccountOrThrow,
  fetchMultipleAccounts,
  fetchProgramAccounts,
  getTokenBalance,
  getSolBalance,
  confirmTransaction,
  getCurrentSlot,
  getBlockTime,
  resolveEndpoint,
  getRecentSignatures,
  buildTransaction,
  buildVersionedTransaction,
  signAndSendTransaction,
  sendAndConfirmTransaction,
  simulateTransaction,
  getTransactionLogs,
  createMemoInstruction,
  estimateTransactionFee,
  getMedianPriorityFee,
  deriveKeypair,
  deriveViewingKeypair,
  deriveSpendingKeypair,
  generateKeypair,
  loadKeypairFromJson,
  keypairToJson,
  computeSharedSecret,
  randomBytes,
  hash256,
} from "./utils";
